export const PLACE_ORDER_REQUEST = "PLACE_ORDER_REQUEST"
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS"
export const PLACE_ORDER_FAIL = "PLACE_ORDER_FAIL"
export const PLACE_ORDER_RESET = 'PLACE_ORDER_RESET'

//showed in Profile
export const ORDER_LIST_MY_REQUEST = 'ORDER_LIST_MY_REQUEST'
export const ORDER_LIST_MY_SUCCESS = 'ORDER_LIST_MY_SUCCESS'
export const ORDER_LIST_MY_FAIL = 'ORDER_LIST_MY_FAIL'
export const ORDER_LIST_MY_RESET = 'ORDER_LIST_MY_RESET'

//showed in Profile
export const ORDER_MY_REQUEST = 'ORDER_MY_REQUEST'
export const ORDER_MY_SUCCESS = 'ORDER_MY_SUCCESS'
export const ORDER_MY_FAIL = 'ORDER_MY_FAIL'